#!/usr/bin/env python3
"""
migrate_bmad_workflow.py - Migrate BMAD workflows to Pennyfarthing format

Converts BMAD workflow format to Pennyfarthing stepped workflow format:
- Parses BMAD workflow.md with YAML frontmatter
- Extracts step files and their frontmatter
- Converts variable syntax ({var-name} -> {var_name})
- Generates workflow.yaml with Pennyfarthing schema
- Preserves tri-modal structure (steps-c, steps-v, steps-e)

Usage: python migrate_bmad_workflow.py [--dry-run] <source-dir> [target-dir]
"""

import argparse
import re
import sys
from pathlib import Path


class Colors:
    RED = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE = '\033[34m'
    NC = '\033[0m'


def log_info(msg: str) -> None:
    print(f"{Colors.BLUE}INFO{Colors.NC}: {msg}")


def log_success(msg: str) -> None:
    print(f"{Colors.GREEN}SUCCESS{Colors.NC}: {msg}")


def log_warn(msg: str) -> None:
    print(f"{Colors.YELLOW}WARN{Colors.NC}: {msg}")


def log_error(msg: str) -> None:
    print(f"{Colors.RED}ERROR{Colors.NC}: {msg}", file=sys.stderr)


def extract_frontmatter(content: str) -> tuple[dict, str]:
    """Extract YAML frontmatter from markdown content."""
    lines = content.split('\n')

    if not lines or lines[0].strip() != '---':
        return {}, content

    end_index = -1
    for i, line in enumerate(lines[1:], 1):
        if line.strip() == '---':
            end_index = i
            break

    if end_index == -1:
        return {}, content

    frontmatter = {}
    for line in lines[1:end_index]:
        match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$', line)
        if match:
            key, value = match.groups()
            value = value.strip().strip('"\'')
            frontmatter[key] = value

    rest_content = '\n'.join(lines[end_index + 1:])
    return frontmatter, rest_content


def convert_variables(text: str) -> str:
    """Convert BMAD-style dashed variables to Pennyfarthing underscore style."""
    result = text
    prev = None

    while result != prev:
        prev = result
        result = re.sub(
            r'\{([a-zA-Z0-9_]+)-([a-zA-Z0-9_-]+)\}',
            lambda m: '{' + m.group(1) + '_' + m.group(2).replace('-', '_') + '}',
            result
        )

    return result


def is_trimodal(source_dir: Path) -> bool:
    """Check if workflow is tri-modal (has steps-c, steps-v, or steps-e)."""
    return any(
        (source_dir / d).exists()
        for d in ['steps-c', 'steps-v', 'steps-e']
    )


def get_step_directories(source_dir: Path) -> list[str]:
    """Get step directories to process."""
    if is_trimodal(source_dir):
        return [d for d in ['steps-c', 'steps-v', 'steps-e']
                if (source_dir / d).exists()]
    elif (source_dir / 'steps').exists():
        return ['steps']
    return []


def get_supporting_directories(source_dir: Path) -> list[str]:
    """Get supporting directories (templates, data, etc.)."""
    return [d for d in ['templates', 'data', 'assets']
            if (source_dir / d).exists()]


def get_root_template_files(source_dir: Path) -> list[str]:
    """Get root-level template files."""
    return [f.name for f in source_dir.iterdir()
            if f.is_file() and '-template' in f.name and f.suffix == '.md']


def copy_dir_with_transform(src_dir: Path, dest_dir: Path,
                            transform: callable, dry_run: bool) -> None:
    """Recursively copy directory with file transformation."""
    if not src_dir.exists():
        return

    if not dry_run:
        dest_dir.mkdir(parents=True, exist_ok=True)

    for entry in src_dir.iterdir():
        dest_path = dest_dir / entry.name

        if entry.is_dir():
            copy_dir_with_transform(entry, dest_path, transform, dry_run)
        elif entry.is_file():
            content = entry.read_text()
            transformed = transform(content, entry)

            if dry_run:
                if content != transformed:
                    log_info(f"[DRY-RUN] Would convert variables in: {entry}")
            else:
                dest_path.write_text(transformed)
                log_success(f"Copied: {dest_path.name}")


def generate_workflow_yaml(name: str, description: str, trimodal: bool) -> str:
    """Generate workflow.yaml content."""
    converted_desc = convert_variables(description)

    if trimodal:
        step_config = """    path: ./steps-c/
    pattern: step-*.md"""
        modes_config = """
  # Tri-modal workflow paths
  modes:
    create: ./steps-c/
    validate: ./steps-v/
    edit: ./steps-e/"""
    else:
        step_config = """    path: ./steps/
    pattern: step-*.md"""
        modes_config = ""

    return f"""# {name} Workflow - Migrated from BMAD format
# Generated by migrate_bmad_workflow.py

workflow:
  name: {name}
  description: {converted_desc}
  version: "1.0.0"
  type: stepped

  # Step configuration
  steps:
{step_config}
{modes_config}
  # Variables available in step files
  variables:
    project_root: .
    planning_artifacts: ./artifacts
    output_file: artifacts/{name}.md

  # Agent assignment (customize as needed)
  agent: architect

  # Triggers - when to suggest this workflow
  triggers:
    types: [{name}]
    tags: [{name}, stepped]
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Migrate BMAD workflows to Pennyfarthing stepped workflow format"
    )
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be done without making changes')
    parser.add_argument('source_dir', type=Path,
                        help='Path to BMAD workflow directory (must contain workflow.md)')
    parser.add_argument('target_dir', type=Path, nargs='?', default=Path('.'),
                        help='Path to output directory (default: current directory)')
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    target_dir = args.target_dir.resolve()
    dry_run = args.dry_run

    if not source_dir.exists():
        log_error(f"Source directory not found: {source_dir}")
        return 1

    workflow_md = source_dir / 'workflow.md'
    if not workflow_md.exists():
        log_error(f"workflow.md not found in {source_dir}")
        return 1

    log_info('BMAD Workflow Migration')
    log_info('=======================')
    log_info(f'Source: {source_dir}')
    log_info(f'Target: {target_dir}')

    if dry_run:
        log_warn('DRY-RUN MODE - No changes will be made')

    print('')

    # Parse workflow.md
    content = workflow_md.read_text()
    frontmatter, _ = extract_frontmatter(content)

    name = frontmatter.get('name')
    description = frontmatter.get('description', '')

    if not name:
        log_error('Could not extract workflow name from workflow.md')
        return 1

    log_info(f'Parsed workflow: {name}')
    log_info(f'Description: {description}')
    print('')

    # Create target directory
    if not dry_run:
        target_dir.mkdir(parents=True, exist_ok=True)

    # Generate workflow.yaml
    log_info('Generating workflow.yaml')
    trimodal = is_trimodal(source_dir)
    workflow_yaml = generate_workflow_yaml(name, description, trimodal)

    if dry_run:
        log_info('[DRY-RUN] Would create: workflow.yaml')
    else:
        (target_dir / 'workflow.yaml').write_text(workflow_yaml)
        log_success('Created workflow.yaml')

    print('')

    # Copy step directories
    def md_transform(content: str, filepath: Path) -> str:
        if filepath.suffix == '.md':
            return convert_variables(content)
        return content

    for dir_name in get_step_directories(source_dir):
        log_info(f'Processing step directory: {dir_name}')
        if dry_run:
            log_info(f'[DRY-RUN] Would copy and transform: {dir_name}/')
        copy_dir_with_transform(
            source_dir / dir_name,
            target_dir / dir_name,
            md_transform,
            dry_run
        )

    print('')

    # Copy supporting directories
    for dir_name in get_supporting_directories(source_dir):
        log_info(f'Processing supporting directory: {dir_name}')
        if dry_run:
            log_info(f'[DRY-RUN] Would copy: {dir_name}/')
        copy_dir_with_transform(
            source_dir / dir_name,
            target_dir / dir_name,
            md_transform,
            dry_run
        )

    print('')

    # Copy root-level template files
    for filename in get_root_template_files(source_dir):
        log_info(f'Processing root template file: {filename}')
        src_path = source_dir / filename
        dest_path = target_dir / filename

        if dry_run:
            log_info(f'[DRY-RUN] Would copy: {filename}')
        else:
            content = src_path.read_text()
            transformed = convert_variables(content)
            dest_path.write_text(transformed)
            log_success(f'Copied: {filename}')

    print('')

    if dry_run:
        log_info('DRY-RUN complete. No files were modified.')
    else:
        log_success('Migration complete!')
        log_info(f'Output directory: {target_dir}')

    return 0


if __name__ == "__main__":
    sys.exit(main())
